#!/usr/bin/env python3
"""Build the ReadingPaper static library. Authored stage HTML is never replaced."""
import html
import json
import re
import copy
import hashlib
import os
from datetime import date
from pathlib import Path
from urllib.parse import urlsplit, unquote, quote

import markdown

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by scripts/build_site.py; edit papers.json or the source Markdown. -->"
STAGES = {"first-pass": "第一遍初读", "deep-read": "第二遍深读", "code": "代码阅读"}
CATEGORIES = {"in-field": "领域内", "out-of-field": "领域外", "uncategorized": "未分类"}
DESCRIPTIONS = {
    "first-pass": "研究问题、核心观察、方法轮廓与作者的论证路径。",
    "deep-read": "摘要、引言与结尾的句段功能、论证衔接和写作语言。",
    "code": "论文框架图、方法公式与固定版本源码的逐模块对照。",
}
esc = html.escape
OUTPUTS = {}


def local_path(value):
    path = (ROOT / value).resolve()
    if not path.is_relative_to(ROOT):
        raise ValueError(f"Path outside repository: {value}")
    return path


def save(path, content):
    local_path(path)
    OUTPUTS[path] = content


def write_pages(outputs):
    # Check ALL destinations before any write (including late-page conflicts).
    for name in outputs:
        path = local_path(name)
        if path.exists() and (not path.is_file() or not path.read_text().startswith('<!doctype html>\n' + MARKER)):
            raise ValueError(f"Refusing to overwrite authored HTML: {name}")
    for name, content in outputs.items():
        path = local_path(name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def review_label(paper, stage):
    review = paper.get("reviews", {}).get(stage, {})
    note = {"draft": "草稿", "organized": "已整理"}.get(review.get("noteStatus"), "整理状态未登记")
    check = f"已登记来源核对 · {review['checkedAt']}" if review.get("status") == "source-checked" else "来源核对未登记"
    return f"{note} · {check}"


def shell(title, body, prefix="", current="library"):
    def asset(name):
        digest = hashlib.sha256((ROOT / 'assets' / name).read_bytes()).hexdigest()[:12]
        return f'{prefix}assets/{name}?v={digest}'

    def nav(href, text, key):
        active = ' aria-current="page"' if current == key else ""
        return f'<a href="{prefix}{href}"{active}>{text}</a>'
    return f'''<!doctype html>
{MARKER}
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} · ReadingPaper</title><meta name="description" content="个人论文阅读库：LiDAR、机器人感知与恶劣天气点云去噪。">
<link rel="icon" href="{prefix}assets/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="{asset('style.css')}"><script src="{asset('app.js')}" defer></script></head>
<body><a class="skip" href="#main">跳到正文</a><div class="layout"><aside class="sidebar">
<a class="brand" href="{prefix}index.html"><span class="brand-mark" aria-hidden="true">R</span>ReadingPaper</a>
<p class="side-caption">个人论文阅读库</p><nav aria-label="主导航">
{nav('index.html', '全部论文', 'library')}{nav('overview.html', '跨论文综述', 'overview')}
</nav><div class="side-note">研究方向<br>机器人感知<br>恶劣天气点云去噪</div></aside>
<main id="main">{body}<footer class="footer">ReadingPaper · 阅读、理解与连接<br>阅读阶段依据已保存的笔记；未整理的阶段不计入完成数量。</footer></main></div></body></html>'''


def stage_tabs(paper, current):
    active = ' aria-current="page"' if current == "index" else ""
    parts = [f'<a href="index.html"{active}>总览</a>']
    for key, label in STAGES.items():
        active = ' aria-current="page"' if current == key else ""
        hint = "" if key in paper["available"] else ("<small>未公开</small>" if paper.get('_public') else "<small>待整理</small>")
        parts.append(f'<a href="{key}.html"{active}>{label}{hint}</a>')
    return '<nav class="reading-tabs" aria-label="阅读阶段">' + ''.join(parts) + '</nav>'


def resources(paper):
    links = []
    if paper.get("pdf"):
        links.append(f'<a href="../{esc(paper["pdf"], quote=True)}">论文 PDF ↗</a>')
    if paper.get("doi"):
        links.append(f'<a href="https://doi.org/{esc(paper["doi"], quote=True)}" target="_blank" rel="noopener">DOI ↗</a>')
    elif paper.get("url"):
        links.append(f'<a href="{esc(paper["url"], quote=True)}" target="_blank" rel="noopener">论文原文 ↗</a>')
    if paper.get("card"):
        links.append(f'<a href="../{esc(paper["card"], quote=True)}">原始 Markdown</a>')
    if paper.get("codeUrl"):
        links.append(f'<a href="{esc(paper["codeUrl"], quote=True)}" target="_blank" rel="noopener">代码仓库 ↗</a>')
    return '<div class="resource-links">' + ''.join(links) + '</div>'


def render_markdown(path, output="overview.html"):
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc", "sane_lists"], extension_configs={"toc": {"toc_depth": "2-3"}})
    text = path.read_text(encoding="utf-8")
    content = md.convert(text)
    # Markdown links are relative to the SOURCE, HTML links to its OUTPUT page.
    def relocate(match):
        key, delimiter, value = match.groups()
        url = urlsplit(html.unescape(value))
        if url.scheme or url.netloc or not url.path:
            return match.group(0)
        target = (path.parent / unquote(url.path)).resolve()
        if not target.is_relative_to(ROOT):
            raise ValueError(f"Markdown link leaves repository: {path.name}: {value}")
        relative = quote(os.path.relpath(target, (ROOT / output).parent), safe="/-._~")
        relative += ("?" + url.query if url.query else "") + ("#" + url.fragment if url.fragment else "")
        return f'{key}={delimiter}{esc(relative, quote=True)}{delimiter}'
    content = re.sub(r'\b(href|src)=([\"\x27])(.*?)\2', relocate, content)
    content = re.sub(r'<table>(.*?)</table>', r'<div class="table-wrap"><table>\1</table></div>', content, flags=re.S)
    toc = f'<details class="toc"><summary>本页目录</summary>{md.toc}</details>' if md.toc_tokens else ""
    return toc + '<article class="prose">' + content + '</article>'


def paper_pages(paper):
    slug = paper["slug"]
    header = f'''<div class="crumb"><a href="../index.html">论文库</a> / {esc(paper['name'])}</div>
<header class="page-head"><div class="eyebrow">{paper['year']} · {esc(paper['venue'])}</div><h1>{esc(paper['name'])}</h1>
<p>{esc(paper['title'])}</p><p class="paper-meta">{CATEGORIES[paper['category']]} · 阅读日期 {esc(paper['readDate'])} · {len(paper['available'])} / 3 个阶段有笔记</p></header>'''
    panels = []
    for number, (key, label) in enumerate(STAGES.items(), 1):
        available = key in paper["available"]
        panels.append(f'''<section class="stage-card"><span class="number">0{number}</span><h2>{label}</h2>
<p>{DESCRIPTIONS[key]}</p><span class="badge{' neutral' if not available else ''}">{'已有笔记' if available else ('未公开' if paper.get('_public') else '尚未整理')}</span>
<p class="review-status">{esc(review_label(paper, key)) if available else ('此阶段未公开' if paper.get('_public') else '')}</p><a href="{key}.html">{'开始阅读 →' if available else '查看阶段说明 →'}</a></section>''')
    note = '<p class="notice">深读内容由已有 Paper Card 转为网页，保留原有分析与结论。第一遍初读和代码阅读独立记录。</p>' if paper.get("card") else ""
    questions = paper.get("openQuestions", [])
    extras = ('<section class="notice"><h2>待核对的问题</h2><ul>' + ''.join(f'<li>{esc(q)}</li>' for q in questions) + '</ul></section>') if questions else ''
    save(f"{slug}/index.html", shell(paper["name"], header + stage_tabs(paper, "index") + f'<p>{esc(paper["summary"])}</p>' + resources(paper) + '<div class="stage-grid">' + ''.join(panels) + '</div>' + extras + note, "../", "paper"))
    for key, label in STAGES.items():
        source = paper['_sources'].get(key)
        if source and source.suffix.lower() == '.html':
            continue
        if source:
            review = paper.get('reviews', {}).get(key, {})
            evidence = ''.join(f'<li>{esc(item)}</li>' for item in review.get('evidence', []))
            content = f'<div class="notice">{esc(review_label(paper, key))}' + (f'<ul>{evidence}</ul>' if evidence else '') + '</div>' + render_markdown(source, f'{slug}/{key}.html')
        else:
            state = '未公开' if paper.get('_public') else '尚未整理'
            explanation = '公开版本不包含此阶段笔记。' if paper.get('_public') else '这篇论文还没有保存此阶段的笔记。'
            content = f'<section class="empty"><h2>{label}{state}</h2><p>{explanation}</p><p>{DESCRIPTIONS[key]}</p><a href="index.html">返回论文总览</a></section>'
        save(f"{slug}/{key}.html", shell(f"{paper['name']} · {label}", header + stage_tabs(paper, key) + content, "../", "paper"))


def build(papers=None, *, write=True, overview=True):
    OUTPUTS.clear()
    papers = copy.deepcopy(papers if papers is not None else json.loads((ROOT / "papers.json").read_text()))
    slugs = set()
    for paper in papers:
        slug = paper["slug"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug) or slug in slugs:
            raise ValueError(f"Invalid or duplicate slug: {slug}")
        slugs.add(slug)
        paper.setdefault('category', 'uncategorized')
        if not isinstance(paper['category'], str) or paper['category'] not in CATEGORIES:
            raise ValueError(f"Invalid category: {slug}; expected one of {', '.join(CATEGORIES)}")
        if not isinstance(paper.get('venue'), str) or not paper['venue'].strip():
            raise ValueError(f"Invalid venue: {slug}; expected a non-empty publication venue")
        paper['venue'] = paper['venue'].strip()
        paper["available"] = set()
        paper['_sources'] = {}
        date.fromisoformat(paper['readDate'])
        for field in ['url', 'codeUrl']:
            if paper.get(field) and (urlsplit(paper[field]).scheme not in ('http', 'https') or not urlsplit(paper[field]).netloc):
                raise ValueError(f"Invalid {field}: {slug}")
        if not isinstance(paper.get('openQuestions', []), list) or not all(isinstance(q, str) for q in paper.get('openQuestions', [])):
            raise ValueError(f"openQuestions must be a list of strings: {slug}")
        for key, value in paper.get("stages", {}).items():
            if key not in STAGES or not isinstance(value, str) or (value != f'{key}.html' and not value.endswith('.md')):
                raise ValueError(f"Stage must reference canonical HTML or a Markdown source: {slug}")
            path = local_path(f"{slug}/{value}")
            if not path.is_file() or MARKER in path.read_text():
                raise ValueError(f"Stage needs authored content: {path}")
            paper["available"].add(key)
            paper['_sources'][key] = path
        for key in ["pdf", "card"]:
            if paper.get(key) and not local_path(paper[key]).is_file():
                raise ValueError(f"Missing {key}: {paper[key]}")
        if paper.get("card"):
            if "deep-read" in paper.get("stages", {}):
                raise ValueError(f"Choose a card OR authored deep-read HTML for {slug}")
            paper["available"].add("deep-read")
            paper['_sources']['deep-read'] = local_path(paper['card'])
        for key, review in paper.get('reviews', {}).items():
            if key not in paper['available'] or review.get('status', 'unrecorded') not in ('unrecorded', 'source-checked') or review.get('noteStatus', 'unknown') not in ('unknown', 'draft', 'organized'):
                raise ValueError(f"Invalid review record: {slug}/{key}")
            if review.get('status') == 'source-checked':
                date.fromisoformat(review['checkedAt'])
                if not review.get('evidence') or not isinstance(review['evidence'], list) or not all(isinstance(e, str) and e.strip() for e in review['evidence']):
                    raise ValueError(f"Source check requires concrete evidence: {slug}/{key}")
    cards = []
    for paper in sorted(papers, key=lambda p: p["readDate"], reverse=True):
        slug = paper["slug"]
        stages = []
        for key, label in STAGES.items():
            if key in paper["available"]:
                stages.append(f'<a href="{slug}/{key}.html">{label} →</a>')
            else:
                stages.append(f'<span class="unavailable">{label} · {"未公开" if paper.get("_public") else "待整理"}</span>')
        status = "已有深读" if "deep-read" in paper["available"] else "已有初读" if "first-pass" in paper["available"] else "已有代码笔记" if "code" in paper["available"] else "待阅读"
        if paper.get('_public') and not paper['available']: status = '未公开笔记'
        searchable = ' '.join([paper['name'], paper['title'], str(paper['year']), paper['venue'], CATEGORIES[paper['category']], *paper['tags'], paper['summary']]).lower()
        checked = sum(paper.get('reviews', {}).get(k, {}).get('status') == 'source-checked' for k in paper['available'])
        verification = f'{checked} 个阶段登记来源核对' if checked else '来源核对未登记'
        cards.append(f'''<article class="paper-card" data-slug="{slug}" data-category="{paper['category']}" data-venue="{esc(paper['venue'], quote=True)}" data-search="{esc(searchable, quote=True)}" data-year="{paper['year']}" data-date="{esc(paper['readDate'], quote=True)}" data-stages="{' '.join(sorted(paper['available']))}">
<div class="card-top"><div class="paper-meta"><span class="year">{paper['year']}</span><span>· {esc(paper['venue'])}</span><span>· 阅读于 {esc(paper['readDate'])}</span></div><span class="badge">{status}</span></div>
<h2><a href="{slug}/index.html">{esc(paper['name'])}</a></h2><p class="paper-title">{esc(paper['title'])}</p>
<p class="paper-summary">{esc(paper['summary'])}</p><div class="tags"><span class="tag category-tag">{CATEGORIES[paper['category']]}</span>{''.join(f'<span class="tag">{esc(tag)}</span>' for tag in paper['tags'])}</div><p class="review-status">{verification}</p><div class="stage-links">{''.join(stages)}</div></article>''')
    counts = {key: sum(key in p['available'] for p in papers) for key in STAGES}
    category_options = ''.join(f'<option value="{key}">{label}（{sum(p["category"] == key for p in papers)}）</option>' for key, label in CATEGORIES.items())
    venues = sorted({p['venue'] for p in papers}, key=str.casefold)
    venue_options = ''.join(f'<option value="{esc(venue, quote=True)}">{esc(venue)}（{sum(p["venue"] == venue for p in papers)}）</option>' for venue in venues)
    home = f'''<header class="page-head"><div class="eyebrow">RESEARCH / READING LIBRARY</div><div class="heading-line"><h1>我的论文库</h1><div class="count">{len(papers):02}<small>篇论文</small></div></div><p>从第一遍初读，到写作精读与方法代码阅读。</p></header>
<div class="stats"><span><strong>{counts['first-pass']}</strong> 篇有初读笔记</span><span><strong>{counts['deep-read']}</strong> 篇有深读笔记</span><span><strong>{counts['code']}</strong> 篇有代码笔记</span></div>
<div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" aria-label="搜索论文" placeholder="搜索标题、方法或关键词…" autocomplete="off"></label>
<select id="category-filter" aria-label="按研究领域筛选"><option value="all">全部领域</option>{category_options}</select>
<select id="venue-filter" aria-label="按期刊或会议筛选"><option value="">全部发表来源</option>{venue_options}</select>
<select id="stage-filter" aria-label="按阅读阶段筛选"><option value="all">全部阶段</option><option value="first-pass">已有初读</option><option value="deep-read">已有深读</option><option value="code">已有代码笔记</option></select>
<select id="sort" aria-label="排序"><option value="recent">最近阅读优先</option><option value="year">发表年份优先</option></select></div>
<div class="list-label"><span id="result-count" role="status" aria-live="polite">{len(papers)} 篇论文</span><span>领域、发表来源与阅读阶段取交集</span></div><div class="paper-list" id="paper-list">{''.join(cards)}</div>
<section class="empty" id="empty" hidden><h2>没有找到匹配的论文</h2><p>试试其他关键词，或切换领域、发表来源与阅读阶段。</p><button id="reset" type="button">清除筛选</button></section>
<noscript><p>所有论文链接均可正常阅读；搜索和筛选需要启用 JavaScript。</p></noscript>'''
    # Validate every input before writing any generated page.
    for paper in papers:
        paper_pages(paper)
    save("index.html", shell("我的论文库", home))
    overview_body = render_markdown(ROOT / 'paper-cards/cross-paper-overview.md') if overview else '<p class="notice">跨论文综述尚未列入公开范围。</p>'
    save("overview.html", shell("跨论文综述", '<header class="page-head"><div class="eyebrow">RESEARCH CONNECTIONS</div><h1>跨论文综述</h1></header>' + overview_body, current="overview"))
    if write:
        write_pages(OUTPUTS)
    print(f"Built library: {len(papers)} papers, {counts}, 2 library pages and {len(papers)*4} paper pages.")
    return dict(OUTPUTS), papers


if __name__ == "__main__":
    build()
