#!/usr/bin/env python3
"""Render a local two-pane PDF/HTML reader for papers with a private PDF."""

import html
import json
from pathlib import Path

from evidence import load_map


STAGES = {
    "first-pass": "第一遍初读",
    "deep-read": "第二遍深读",
    "code": "代码阅读",
}


def local_pdf_path(root, slug, data=None):
    data = data or load_map(root, slug)
    if not data:
        return None
    local_pdf = data.get("viewer", {}).get("local_pdf")
    if not local_pdf:
        return None
    path = (Path(root) / "papers" / slug / local_pdf).resolve()
    paper_dir = (Path(root) / "papers" / slug).resolve()
    if not path.is_relative_to(paper_dir) or not path.is_file():
        return None
    return path


def available(root, slug, data=None):
    return local_pdf_path(root, slug, data) is not None


def render(root, paper):
    """Return generated linked-reader HTML, or an empty string when unavailable."""
    root = Path(root).resolve()
    slug = paper["slug"]
    data = load_map(root, slug)
    pdf_path = local_pdf_path(root, slug, data)
    if data is None or pdf_path is None:
        return ""
    stages = [stage for stage in STAGES if stage in paper.get("available", set())]
    if not stages:
        stages = ["first-pass"]
    default_stage = data.get("viewer", {}).get("default_stage", stages[0])
    if default_stage not in stages:
        default_stage = stages[0]
    stage_buttons = "".join(
        f'<button type="button" class="reader-stage" data-stage="{html.escape(stage)}">{html.escape(STAGES[stage])}</button>'
        for stage in stages
    )
    title = html.escape(paper.get("name", slug))
    pdf_href = pdf_path.relative_to(root / "papers" / slug).as_posix()
    map_json = json.dumps(data, ensure_ascii=False).replace("<", "\\u003c")
    stage_json = html.escape(json.dumps(stages, ensure_ascii=False), quote=True)
    return f'''<!doctype html>
<!-- Generated by scripts/build_site.py; edit papers.json or the source Markdown. -->
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} · 双栏联动阅读 · ReadingPaper</title>
<link rel="stylesheet" href="../../assets/evidence-reader.css">
</head><body class="linked-reader" data-paper="{html.escape(slug, quote=True)}" data-map="evidence-map.json" data-pdf="{html.escape(pdf_href, quote=True)}" data-default-stage="{html.escape(default_stage, quote=True)}" data-stages='{stage_json}'>
<header class="reader-toolbar"><div class="reader-title"><a href="index.html">← {title}</a><span>双栏联动阅读</span></div><nav aria-label="阅读阶段">{stage_buttons}</nav><span id="reader-status" role="status">右侧点击笔记内容，左侧跳到对应 PDF 页</span></header>
<main class="reader-split"><section class="pdf-pane" aria-label="论文 PDF"><div class="pane-heading"><strong>PDF 原文</strong><span id="pdf-location">加载中</span></div><div class="pdf-controls" aria-label="PDF 控制"><button id="pdf-prev" type="button" title="上一页">‹</button><label>第 <input id="pdf-page" type="number" min="1" value="1" aria-label="PDF 页码"> 页 / <span id="pdf-total">–</span></label><button id="pdf-next" type="button" title="下一页">›</button><a id="pdf-open" href="{html.escape(pdf_href, quote=True)}" target="_blank" rel="noopener">系统 PDF ↗</a></div><div id="pdf-quote" class="pdf-quote" hidden><span>对应原文位置</span><blockquote id="pdf-quote-text"></blockquote></div><div id="pdf-viewer" class="pdf-viewer" data-pdf-src="{html.escape(pdf_href, quote=True)}"><div id="pdf-loading" class="pdf-loading">正在加载 PDF…</div></div><noscript><p class="pdf-noscript"><a href="{html.escape(pdf_href, quote=True)}">打开 PDF 原文</a></p></noscript></section><section class="note-pane" aria-label="HTML 阅读笔记"><div class="pane-heading"><strong>阅读笔记</strong><span>点击证据段落，左侧跳到 PDF 页和近似位置</span></div><iframe id="note-viewer" title="{title} 阅读笔记" src="{html.escape(default_stage, quote=True)}.html"></iframe></section></main>
<script id="reader-map" type="application/json">{map_json}</script>
<script type="module" src="../../assets/evidence-reader.js"></script></body></html>'''
